server:
  port: 8080

spring:
  kafka:
    bootstrap-servers: ${KAFKA_BROKER:localhost:9092}
    consumer:
      group-id: orchestrator-service-group
      auto-offset-reset: latest
#    todo: criar arquivo para manter  as variaveis de ambiente, para não precisar ficar alterando o application.yml

logging:
  level:
    org:
      apache:
        kafka: OFF